# Generated by Django 2.2.19 on 2021-06-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_currente', models.IntegerField(max_length=4, verbose_name='Ano currente')),
                ('semestre_currente', models.CharField(choices=[('1', '.1'), ('2', '.2')], max_length=2, verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
